version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "typos"  # ignore patch updates
        update-types: ["version-update:semver-patch"]
