name: Lint Code Base

on:
  workflow_dispatch:
  push:
    branches:  # ignore pushed tags
      - "*"
    paths:
      - '**.py'
      - '**.md'
  pull_request:
    paths:
      - '**.py'
      - '**.md'

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: python -m pip install -e .[dev]
      - run: python -m black --check .
      - run: python -m mypy .
      - run: python -m ruff .
      - uses: crate-ci/typos@v1.16.25
