name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    environment:
      name: pypi
      url: https://pypi.org/p/mediawiki_langcodes
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6

      - name: Build package
        run: |
          python -m pip install -U pip
          python -m pip install .[dev]
          make

      - run: gh release create ${{ github.ref_name }} dist/*
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TELEMETRY: false

      - uses: pypa/gh-action-pypi-publish@release/v1
